-- Crear esquema
CREATE SCHEMA IF NOT EXISTS modulo5;

SET search_path TO modulo5;

-- Eliminar tablas si existen
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS rental CASCADE;

-- ==========================
-- TABLA RENTAL
-- ==========================
CREATE TABLE rental (
    rental_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id NUMERIC(8,0) NOT NULL,
    title TEXT NOT NULL,
    customer_id INTEGER NOT NULL,
    fullName TEXT NOT NULL,
    staff_id SMALLINT NOT NULL,
    category_name TEXT NOT NULL,
    status TEXT NOT NULL,,
    rental_date TIMESTAMP NOT NULL
    return_date TIMESTAMP,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	rental_duration INTEGER NOT NULL,
	penalty_status TEXT NOT NULL,
	fee NUMERIC(5,2) NOT NULL
);

-- ==========================
-- TABLA PAYMENT
-- ==========================
CREATE TABLE payment (
    payment_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    fullName TEXT NOT NULL,
    staff_id SMALLINT NOT NULL,
    rental_id INTEGER NOT NULL,
    amount NUMERIC(5,2) NOT NULL,
    status TEXT NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_rental
        FOREIGN KEY (rental_id)
        REFERENCES rental(rental_id)
        ON DELETE CASCADE
);